#include "Uart_cfg.h"

UartConfig_t UartConfig[] =
{
	{ UART0, UART_DISABLE, CTL_DISABLE, 0u, 0u, FIVE_BITS, ONE_STOPBIT, PAR_DISABLE, SYS_CLOCK},
	{ UART1, UART_DISABLE, CTL_DISABLE, 0u, 0u, FIVE_BITS, ONE_STOPBIT, PAR_DISABLE, SYS_CLOCK},
	{ UART2, UART_DISABLE, CTL_DISABLE, 0u, 0u, FIVE_BITS, ONE_STOPBIT, PAR_DISABLE, SYS_CLOCK},
	{ UART3, UART_DISABLE, CTL_DISABLE, 0u, 0u, FIVE_BITS, ONE_STOPBIT, PAR_DISABLE, SYS_CLOCK},
	{ UART4, UART_DISABLE, CTL_DISABLE, 0u, 0u, FIVE_BITS, ONE_STOPBIT, PAR_DISABLE, SYS_CLOCK},
	{ UART5, UART_DISABLE, CTL_DISABLE, 0u, 0u, FIVE_BITS, ONE_STOPBIT, PAR_DISABLE, SYS_CLOCK},
	{ UART6, UART_DISABLE, CTL_DISABLE, 0u, 0u, FIVE_BITS, ONE_STOPBIT, PAR_DISABLE, SYS_CLOCK},
	{ UART7, UART_DISABLE, CTL_DISABLE, 0u, 0u, FIVE_BITS, ONE_STOPBIT, PAR_DISABLE, SYS_CLOCK}
};

UartConfig_t * Uart_GetConfig(void)
{
	return UartConfig;
}
